### ISSUE TITLE
Collapse task description if too big

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#10]
The experiment description on the "tasks" comparison table may get too long, e.g. for QT leap we have to include there two long strings and a date. This makes the table ugly and difficult to read. It would be nice if only the beginning of the description is shown and that the whole text is shown only if the user clicks on a small arrow or sth like that. I guess this would be easy with some JS trick

**Comment by choko** [comment]
Done in 1526d68817d68ad24678ea374f2635f4ee32220d.

**Comment by lefterav** [comment]
It works
