### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#15]
I had to manually modify the template file in order to change the title. It would be nice if this could be done via the configuration file.
This is what I modified in my version

```
./app/templates/@layout.latte:5:		<title>QTLeap Evaluation Workbench</title>
./app/templates/@layout.latte:48:						<a class="brand" href="/">QTLeap Evaluation Workbench</a>
```

**Comment by choko** [comment]
Done in ee9bfbfcf5e9d136ce16bff462d9adeb532ea535.

Title can be configured in app/config/config.neon.
