### ISSUE TITLE
Basic ordering of experiments

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#16]
Experiments in main screen are ordered in an arbitrary way. I was not able to find a way to manipulate the order that the experiments are displayed (e.g. by modifying the name or their order in the hard disk folder). 

What I did as a simple quick solution was to modify the code for retrieving the experiments, so that they are ordered by name. This makes it easier for the case of QTleap

app/model/Experiments.php:15
        public function getExperiments() {
                return $this->db->table( 'experiments' )
                        ->where( 'visible', 1 )
                        ->order( 'name' );

I haven't yet had the opportunity to sync my local version (from the zip file) with the repository version, because this will most probably break the live qtleap website. So the code above has not been pushed yet. Feel free to modify yourself or I will do when I get into syncing.

**Comment by choko** [comment]
Done in 7c9d562a75a89e6ae944ae74715ba72ee286d9cf.

**Comment by martinpopel** [comment]
The table is sorted OK according to the column clicked. However, the graph above stays the same.
It would be nice if the columns (systems) are sorted in the same way as the table (so the line corresponding to the selected metric is non-decreasing). Main use case is when there are different systems (not different versions of the same system), but I think if the user wants to sort the table by BLEU, then it make sense to sort the graph as well (even if there are different versions of the same system).

**Comment by martinpopel** [comment]
I am sorry, the comment above should go to Issue #18 .
