### ISSUE TITLE
Task table: clickable ordering of systems based on each metric/column

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#18]
in tasks/?experimentId=1 the systems are ordered alphabetically based on their name. A nice feature would be to have a clickable/sortable table. When somebody clicks on the column label "BLEU" the entire table gets sorted by the BLEU value. etc.

**Comment by choko** [comment]
Done in e6094816aa92a6b2de49fb44fba9ffb89223eb52.

**Comment by martinpopel** [comment]
The table is sorted OK according to the column clicked. However, the graph above stays the same.
It would be nice if the columns (systems) are sorted in the same way as the table (so the line corresponding to the selected metric is non-decreasing). Main use case is when there are different systems (not different versions of the same system), but I think if the user wants to sort the table by BLEU, then it make sense to sort the graph as well (even if there are different versions of the same system).

**Comment by choko** [comment]
This one was tough. Done in c4a78bdb7f7d8d7f5b789cc7f835f49f869f26a3. See http://quest.ms.mff.cuni.cz:7280/tasks/?experimentId=18.
