### ISSUE TITLE
Task graph: Possibility to switch to vertical bars instead of a continuous line

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#19]
For comparisons like WMT, where the systems compared are not an evolution of each other, but rather independent from each other, it makes more sense to have vertical bars in the graph, instead of a continous line. This could be possible to change through the interface with a button or sth similar.

**Comment by choko** [comment]
Done in 5555ba05baf3b4d927a6345b23b7381e3e23c1ac.

**Comment by martinpopel** [comment]
I see the buttons "line" and "column" for half a second when loading the page, but then they disappear (so I cannot click on them).

**Comment by choko** [comment]
Fixed in 8f2116a45b38d9b13cf707fa793ccbf406603aa4. See http://quest.ms.mff.cuni.cz:7280/tasks/?experimentId=18
