### ISSUE TITLE
Metadata file should support full text

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#20]
The name and the description of tasks and experiments can be done through a configuration metadata file. The current format raises a lot of errors, if the descriptions contains full text with punctuation, urls etc. The desired functionality would expect the possibility for a more rich format for the description

**Comment by choko** [comment]
You can use any character you want, but you have to enclose the string in "". You can try it online at http://ne-on.org/. If you want to write multiline text, you have to use \n.

Is there anything else you would like to support?
