### ISSUE TITLE
System names missing in Sentences tab

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#21]
See e.g. http://quest.ms.mff.cuni.cz:7280/tasks/75-79/compare

The system names are empty everywhere (the drop-down list at the top, row headers, checkbox/radiobox descriptions "Show" / "Show diff for ").
It would be enough to call it SystemA and SystemB if the real name  is too long (but show the mapping to the real name at least once on the screen).

**Comment by choko** [comment]
Done in b2521433008a25a09b2ff761421b1a93e189d33b. See http://quest.ms.mff.cuni.cz:7280/tasks/75-79/compare.
