### ISSUE TITLE
Highlight sentences with colors by default

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#22]
I think it is better to have all three checkboxes "Highlight confirmed/improving/worsening n-grams" checked by default.
* I think the new users will be more likely to see that there is such a functionality.
* I always use one of the highlighting options and quite often even all three combined.

**Comment by choko** [comment]
Done in 0a8469acfd37c2d3c794500fa51ad557b26ec80d. See http://quest.ms.mff.cuni.cz:7280/tasks/75-79/compare.
