### ISSUE TITLE
vendor directory missing

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#29]
In a fresh installation, I cannot get the system working. I am getting the following error:

```
Warning: require(/local/qtleap/workbench_frontend/app/../vendor/autoload.php): failed to open stream: No such file or directory in /local/qtleap/workbench_frontend/app/bootstrap.php on line 4

Fatal error: require(): Failed opening required '/local/qtleap/workbench_frontend/app/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /local/qtleap/workbench_frontend/app/bootstrap.php on line 4
```

**Comment by lefterav** [comment]
I managed to get back the `vendor` directory by running 
```
curl -s http://getcomposer.org/installer | php
php composer.phar create-project nette/sandbox myApp dev-release-2.0.x
```

I am confused on whether the user should re-initialize a Nette application with the above commands or whether we should provide the directory `vendor` from the beginning. In any case the Readme.md is misleading and lets the user create a new app, myApp.

**Comment by choko** [comment]
It should be fixed now.

**Comment by lefterav** [comment]
yep
