### ISSUE TITLE
Watcher: Infinite loop and log flooding when import errors occur

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#34]
Whenever there is an import error, the watcher keeps trying again and again to import the particular task. This creates huge error logs which eventually fill in all the disk space. 

Additionally, there is no way for the user to fix the erroneously imported file. The problem is that even if the erroneous folder gets deleted and re-imported, the watcher will still complain that the url_key already exists in the database. The only possibility is that the user manually removes the erroneous task or experiment from the database. 

I cannot be more specific on how this can be solved, maybe there were some steps that I was missing and need to be better documented, or something needs to change in the watcher's behaviour.

**Comment by choko** [comment]
Is there a .notimported file in that task folder?

**Comment by lefterav** [comment]
I'm sorry. in the end I deleted the folder, I also deleted manually the task and experiment entries from the database and I re-imported the folder.

**Comment by choko** [comment]
Ok, don't worry. I will try to simulate it and I will try to fix it.

**Comment by lefterav** [comment]
So, to clarify: the import error occurred in two cases because of invalid config.neon

(a) the experiment config.neon pointed to a reference.txt file that had not been created . Then the watcher was trying constantly to locate the reference file, although it was not there

(b) the task config.neon had bad formatting. In particular, there were unclosed quotes, because a linebreak accidentally happened within the description field. Then the watcher was complaining constantly about the illegal line and did not import the task. The tricky thing was, that it complained about the line, but it did not say which exactly path the problem occurred at. 

 I had to find and fix the badly formatted line, but this was not enough, because then watcher complained that the url_key already exists. So I had to delete the experiment to free the url_key.

**Comment by choko** [comment]
Ok, thank you for the report. I think that I fixed the problem in 7026c12.

Now, I would like to add better error messages for (a) and (b).

**Comment by choko** [comment]
I also solved (a) in ac90f0856280f32e84b2cc5c0b8700345aaa560c and (b) in e4046e1801bf267d99023980f8a459527adb3737.

**Comment by choko** [comment]
I discovered one mor bug. It is fixed in 0f422fbcc803bd91ef8b65579a18c3b2f7d0b561.

**Comment by martinpopel** [comment]
@lefterav @jnehring Can you please check all your issues with the tag "waiting for review" and close them or report if there is still some problem? (I would like to lower the number of long-open issues, so there is a "space" for reporting new issues.)
