### ISSUE TITLE
Title bar link "MT-ComparEval"

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#35]
The link at http://workbench.qtleap.eu/evaluation/ points to http://workbench.qtleap.eu/, i.e. `/`, but it should point to `/evaluation/`.

**Comment by choko** [comment]
It was already fixed in 20fc03b56bb496649cfac0063f38832bee2cf5e7.

**Comment by martinpopel** [comment]
Ok, so this issue just waits for DFKI (@jnehring) to update the server.

**Comment by jnehring** [comment]
I updated the server.
