### ISSUE TITLE
show_administration: true in config.neon

### ISSUE THREAD

**Issue by jnehring** [choko/MT-ComparEval#37]
We added password protection to MT-ComparEval and therefore set `show_administration: true` on the server. Now the server config differs from the config on GitHub which says `show_administration: false`.

Can we update the default config to `show_administration: true` so I dont have to manually change the configuration upon each update? This manual task upon each update asks for problems.

**Comment by choko** [comment]
Yes, you can do it.

**Comment by jnehring** [comment]
done
