### ISSUE TITLE
Configurable case-sensitivity

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#43]
Now all metrics are case sensitive by default and for all metrics a case-insensitive (cis) variant is computed. The Tasks screen shows only the case-sensitive metrics.

This is not ideal because the official BLEU (as it was originally defined and as it is usually reported) is case insensitive. Also with more metrics (Hjerson) it takes too long to compute all twice. I would setup the configuration file to compute BLEU (case-insensitive), BLEU (case-sensitive) and all the other metrics (Precision, Recal, F-Measure, 5 Hjerson metrics) only in their "default" variant (which is case-sensitive, I think).

It would be nice if different users can setup the configuration differently.

**Comment by martinpopel** [comment]
Once this is done, I hope I can close also #5.

**Comment by martinpopel** [comment]
See  https://github.com/choko/MT-ComparEval/tree/importer-case-sensitive

**Comment by choko** [comment]
Closed by #51
