### ISSUE TITLE
Compute bootstrap only for some metrics

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#44]
It should be possible to specify in the config file that bootstrap resampling (especially the paired one) is to be computed only for some metrics. The default should be to compute it only for BLEU case-insensitive.
This should make the importing much faster (and the database smaller).

Even better would to let the bootstrap resampling (for metrics and systems for which it was not precomputed so far) be computed lazily: on user request via the web interface.

**Comment by martinpopel** [comment]
See  https://github.com/choko/MT-ComparEval/tree/importer-case-sensitive

**Comment by choko** [comment]
Closed by #51
