### ISSUE TITLE
So many zeros

### ISSUE THREAD

**Issue by jnehring** [choko/MT-ComparEval#46]
I have installed the new version of MT-ComparEval on a DFKI server. The new metrics show mostly zero. See example [here](http://workbench.qtleap.eu/evaluation_demo/tasks/8-9/compare) or the screenshot:

![image](https://cloud.githubusercontent.com/assets/10537540/10241754/e945e30c-68eb-11e5-8067-dd7c0c59ac3d.png)

This looks like a bug to me. I am not sure to whom to assign this issue.

**Comment by martinpopel** [comment]
I installed the new version yesterday and I see all metrics non-zero (for CS->EN batch2q Pilot0 and Pilot1). However, the import now takes 3 hours for one task! So we really need to fix #44 . Meanwhile, I will probably comment out the Hjerson metrics from the default config file. 

> I am not sure to whom to assign this issue.
Hjerson was added by @pompomon.

@jnehring:
Can you check if the Python script (for computing Hjerson, by Maja Popovic) has not died?
Can you replicate the problem on a small data set (10 sentences)?
Can you share this data set (upload it somewhere)?

**Comment by jnehring** [comment]
> Can you check if the Python script (for computing Hjerson, by Maja Popovic) has not died?

I did not run a python script. After installation I only ran bin/watcher.sh which runs a PHP script. Maybe thats the problem. Can you point me to the python script?

> Can you replicate the problem on a small data set (10 sentences)?
Can you share this data set (upload it somewhere)?

Will do.

**Comment by martinpopel** [comment]
[The script](https://github.com/choko/MT-ComparEval/blob/master/external/hjerson%2B.py) should be run automatically by the watcher. See [Hjerson.php](https://github.com/choko/MT-ComparEval/blob/master/libs/Metrics/Hjerson.php). Maybe you can add some logging there (e.g. add ` 2> log$hashId.stderr | tee log$hashId.stdout |` to the `$externalCmd` on line 11).

**Comment by jnehring** [comment]
I downloaded the latest sources and re-run the importer. Now the problem of this issue does not occur. The metrics that produced the zeros are disabled by configuration and the respective table cells are empty.

**Comment by martinpopel** [comment]
Yes, I disabled Hjerson in the default config because of #48 .

@jnehring: Can you improve Hjerson, so it can be integrated in a faster way? Can I assign you to #48 ?

**Comment by jnehring** [comment]
> Can you improve Hjerson, so it can be integrated in a faster way? Can I assign you to #48 ?

Sorry I dont have time to implement new features. I am responsible for maintaining the MT CompareEval installation of DFKI and cannot take new duties.

**Comment by lefterav** [comment]
Closed as reported to be solved
