### ISSUE TITLE
Watcher deletes data folder

### ISSUE THREAD

**Issue by jnehring** [choko/MT-ComparEval#55]
I reinstalled MT ComparEval. Then I ran the watcher. It does not import anything but deletes the data folder. There are two problems:

a) It deletes the data folder. This seems to be quiet critical to me.
b) The database is read only. I expect this is my fault.

The log on the console:

```
Watcher is watching folder: ./data
[14-Dec-2015 16:11:45]  New experiment called bg-en-batch2q was found
[14-Dec-2015 16:11:45]  SQLSTATE[HY000]: General error: 8 attempt to write a readonly database
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<style>
        body { color: #333; background: white; width: 500px; margin: 100px auto }
        h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
        p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
        small { font-size: 70%; color: gray }
</style>

<h1>Server Error</h1>

<p>We're sorry! The server encountered an internal error and
was unable to complete your request. Please try again later.</p>

<p><small>error 500</small></p>
```

and in /log/error.log:

```
[2015-12-14 16-11-45] UnexpectedValueException: RecursiveDirectoryIterator::__construct(./data): failed to open dir: No such file or directory in /local/qtleap/workbench_frontend_demo/vendor/nette/finder/src/Finder/Finder.php:229  @  CLI: www/index.php Background:Watcher:Watch --folder=./data  @@  exception--2015-12-14--16-01--8c922ec955.html
```

**Comment by martinpopel** [comment]
I cannot replicate this bug. I did a fresh git clone now, ran `bin/install.sh`, copied there `data` with some experiments&tasks, ran `bin/watcher.sh` and everything works as expected.
Perhaps you used some non-standard setup, but have not described which one.

**Comment by jnehring** [comment]
I think the problem was that I created a read only database. The linux file system permissions did not allow the user that ran the watcher to write to the database file. This happens when I run the install script as root user but the watcher as non-root. This is of course a non-standard setup, but might be a common pitfall.

**Comment by josemonteiro** [comment]
Having the same issue (watcher deleting data folder).

Steps to reproduce:
1) Create new experiment with description containing a comma (e.g. "experiment x, based on y")
2) watcher.sh outputs
```
[02-Feb-2017 18:31:34]	Error occured during parsing of the configuration file ./data/en-es-neural-ape/config.neon: Unexpected ',' on line 2, column x.
[02-Feb-2017 18:31:34]	Parsing of new-experiment aborted!
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<style>
	body { color: #333; background: white; width: 500px; margin: 100px auto }
	h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
	p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
	small { font-size: 70%; color: gray }
</style>

<h1>Server Error</h1>

<p>We're sorry! The server encountered an internal error and
was unable to complete your request. Please try again later.</p>

<p><small>error 500</small></p>
```
3) Folder data is deleted and watcher.sh dies

In summary, introducing a comma in the description of an experiment will delete all the data. This is extreme.

**Comment by choko** [comment]
Hi Jose,

thank you for reporting this bug, it should be fixed now.

BTW If you want to use special characters in the configuration, put quotes around the whole string.

```
name: 'experiment X, based on Y'
```

Ondrej
