### ISSUE TITLE
PHP7 yields compile errors in ArithmeticRecall.php and GeometricRecall.php

### ISSUE THREAD

**Issue by jgwinnup** [choko/MT-ComparEval#56]
When I use PHP7, I get the following error for ArithmeticRecall and GeometricRecall classes:

Redefinition of parameter $reference in .../ArithmeticRecall.php:15 (similar for GeometricRecall).

I changed the method signature from: 
```
public function addSentence( $reference, $reference, $meta ) {
```

to
```
public function addSentence( $reference, $reference1, $meta ) {
```

in both cases to get the application working, but I'm not sure if that's the correct thing to do.

**Comment by choko** [comment]
Hello Jeremy, thank you for the information. I fixed it to:

```
public function addSentence( $reference, $translation, $meta ) {
```
