### ISSUE TITLE
Unconfirmed "a" shows nothing

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#59]
In http://quest.ms.mff.cuni.cz:7280/tasks/56-59/compare select Unconfirmed and click on unigram "a" in CU-TectoMT loses. It should show 1065 cases when "a" was unconfirmed in TectoMT, but not in uedin-jhu-phrase, but no sentence is shown. Other n-grams work OK (but they have less than 1000 cases).

**Comment by choko** [comment]
Problem is with HTTP/1.1 414 Request-URI Too Long. The request should be rewritten to use POST instead of GET.
