### ISSUE TITLE
Download metrics scores in csv

### ISSUE THREAD

**Issue by martinpopel** [choko/MT-ComparEval#61]
Today, I (well, @mjpost) wanted to download all WMT15 BLEU scores from wmt.ufal.cz. It would be nice to have a button for downloading a csv file where
lines = all systems (tasks) from all experiments
columns = experiment_name, task_name, task_description, all metrics scores
The header line should include the metrics names.

One could imagine a configuration dialog where the users select which metrics and which experiments/tasks they are interested in, but I think that's not worth the work. The users can filter the csv themselves (e.g. by importing it to Excel).

**Comment by choko** [comment]
Done in c41599066b7c947ff5fa90ef88c29f539acc1917.
