### ISSUE TITLE
Experiment name should be displayed on top of the "Task" page

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#7]
When one clicks to see a particular experiment details (where the graph and all systems listed) the name of the experiment is no longer displayed, just the page title contains only the title "Tasks". It would be useful if the experiment name and description can be displayed above of the graph.

**Comment by choko** [comment]
Done in 29af6d4b0438f9d38174081e958e5b811fb92dcc.

**Comment by lefterav** [comment]
It works
