### ISSUE TITLE
.bat scripts for windows installation and execution

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#72]
I am not sure how this can be done, but it would be possible to offer generic .bat scripts for Windows similar to the ones existing for Linux

**Comment by martinpopel** [comment]
The bin/install.sh script is quite simple, but it contains curl. I am not Windows expert, but I think there is no always-available alternative in old .bat scripts. You can use PowerShell https://superuser.com/a/330754, but Windows users will be probably happy with instructions like "right click and Save as":-).
BTW: I have heard that Windows 10’s Anniversary Update brings a “Bash on Ubuntu on Windows”.

**Comment by lefterav** [comment]
Thanks, I was asked to make it compatible with Windows 7, so I have already figured out all the  compatible tools for it. 

I think most work of the installation script is done not with curl but with composer and git, which are both available in Windows. The tricky thing is specifying the installation path because this varies between systems.

Additionally one has to launch server and watcher on the commandline which is non-trivial for a windows user, so I was thinking also about that
