### ISSUE TITLE
TER support

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#76]
Include metric TER as an external metric

**Comment by martinpopel** [comment]
So is not this done?

**Comment by lefterav** [comment]
Sorry, forgot to close the ticket. This has been implemented and tested. The implementation was based by including a compiled binary version of TERp v.0.6.2, as an external library, which was available open-source by https://github.com/cservan/tercpp and is also available in a Debian package. There could have been a later version of TERp but this was more stable and tests show that results are comparable.
