### ISSUE TITLE
Allow for editing experiment and task names and descriptions

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#8]
The names and description of experiments and "tasks" cannot be changed through the graphical interface after the system has been imported from the hard disk. A modification in the interface might allow the possibility to change them afterwards through the GUI

**Comment by choko** [comment]
Done in 944a44fdf976e8dea51fa04dc893ab263293bc80 and 3d2245598d0d75819240b16b1573aa45cc76ae97.

**Comment by lefterav** [comment]
Hi. Editing title and description works fine. There is a small usability issue. After clicking "Save", the user stays in the same editing form. There is no possibility or button to go back to the listing table, unless one clicks the [back] browse button twice, which is not optimal.

The most obvious would be, after clicking on [save] to go to the table that sent you there.

**Comment by choko** [comment]
Done in 247baf543cbb1ceb31a490bf07cf7a30666e5bb1.
