### ISSUE TITLE
Ask for a confirmation before deleting experiments and tasks

### ISSUE THREAD

**Issue by lefterav** [choko/MT-ComparEval#9]
The graphical interface allows for deleting experiments and "tasks". Once the user clicks that, the relevant entry disappears immediately and there is no way of recovering it. For better system user interaction, there should be a confirmation screen, where the user is asked "Do you really want to delete this? There is no way to undo this action"

**Comment by choko** [comment]
Done in a5882a85f2ceba491fdd9747b4f2c25664cc6419.

**Comment by lefterav** [comment]
It works
